services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: medusa-meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ms
    volumes:
      - ./.meili-data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 10
